#!/bin/bash

# Linux Server Hardening Script
# Task 4: Linux Server Hardening
# Author: Cybersecurity Student

set -e  # Exit on any error

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m' # No Color

# Logging function
log() {
    echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

# Check if running as root
if [[ $EUID -eq 0 ]]; then
   error "This script should not be run as root for security reasons"
   exit 1
fi

# Check if sudo is available
if ! command -v sudo &> /dev/null; then
    error "sudo is required but not installed"
    exit 1
fi

log "Starting Linux Server Hardening Process..."

# Create backup directory
BACKUP_DIR="/tmp/hardening_backup_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BACKUP_DIR"
log "Created backup directory: $BACKUP_DIR"

# Phase 1: System Information and Baseline
log "Phase 1: Gathering system information..."

# System info
uname -a > "$BACKUP_DIR/system_info.txt"
lsb_release -a >> "$BACKUP_DIR/system_info.txt" 2>/dev/null
ip addr show > "$BACKUP_DIR/network_info.txt"
netstat -tulpn > "$BACKUP_DIR/open_ports_before.txt"
systemctl list-units --type=service --state=running > "$BACKUP_DIR/running_services.txt"

success "System information gathered"

# Phase 2: SSH Hardening
log "Phase 2: Hardening SSH configuration..."

# Backup SSH config
sudo cp /etc/ssh/sshd_config "$BACKUP_DIR/sshd_config.backup"

# Create hardened SSH config
cat << 'EOF' | sudo tee /etc/ssh/sshd_config.hardened > /dev/null
# Hardened SSH Configuration
# Generated by Linux Server Hardening Script

# Network settings
Port 2022
Protocol 2
AddressFamily inet

# Authentication settings
PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no

# User restrictions
AllowUsers $(whoami)
MaxAuthTries 3
MaxSessions 2

# Connection settings
ClientAliveInterval 300
ClientAliveCountMax 2
LoginGraceTime 60

# Logging
SyslogFacility AUTH
LogLevel INFO

# Disable unused authentication methods
KerberosAuthentication no
GSSAPIAuthentication no
X11Forwarding no
PermitUserEnvironment no
EOF

# Apply SSH configuration
sudo cp /etc/ssh/sshd_config.hardened /etc/ssh/sshd_config

# Test SSH configuration
if sudo sshd -t; then
    success "SSH configuration is valid"
    sudo systemctl restart sshd
    success "SSH service restarted"
else
    error "SSH configuration is invalid, restoring backup"
    sudo cp "$BACKUP_DIR/sshd_config.backup" /etc/ssh/sshd_config
    sudo systemctl restart sshd
    exit 1
fi

# Phase 3: Firewall Configuration
log "Phase 3: Configuring UFW firewall..."

# Install UFW if not present
if ! command -v ufw &> /dev/null; then
    sudo apt update
    sudo apt install -y ufw
fi

# Reset and configure UFW
sudo ufw --force reset
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 2022/tcp comment 'SSH'
sudo ufw logging on
sudo ufw --force enable

success "UFW firewall configured and enabled"

# Phase 4: Install and Configure fail2ban
log "Phase 4: Setting up fail2ban..."

# Install fail2ban
if ! command -v fail2ban-client &> /dev/null; then
    sudo apt update
    sudo apt install -y fail2ban
fi

# Create fail2ban local configuration
cat << 'EOF' | sudo tee /etc/fail2ban/jail.local > /dev/null
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 3
backend = systemd

[sshd]
enabled = true
port = 2022
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 3600
EOF

# Start and enable fail2ban
sudo systemctl enable fail2ban
sudo systemctl restart fail2ban

success "fail2ban configured and started"

# Phase 5: Final verification
log "Phase 5: Performing final verification..."

# Check services status
systemctl is-active sshd >/dev/null && success "SSH service is running" || error "SSH service is not running"
systemctl is-active ufw >/dev/null && success "UFW service is running" || error "UFW service is not running"
systemctl is-active fail2ban >/dev/null && success "fail2ban service is running" || error "fail2ban service is not running"

# Generate post-hardening report
netstat -tulpn > "$BACKUP_DIR/open_ports_after.txt"
sudo ufw status verbose > "$BACKUP_DIR/ufw_status.txt"
sudo fail2ban-client status > "$BACKUP_DIR/fail2ban_status.txt"

# Display summary
log "Hardening completed successfully!"
echo
echo "Summary of changes:"
echo "- SSH hardened (root login disabled, key auth only, port 2022)"
echo "- UFW firewall enabled with restrictive rules"
echo "- fail2ban configured for intrusion prevention"
echo
echo "Backup files stored in: $BACKUP_DIR"
echo
warning "IMPORTANT: Test SSH connectivity before closing this session!"
warning "New SSH command: ssh -p 2022 $(whoami)@$(hostname -I | awk '{print $1}')"